name: Hello World Test

on:
  repository_dispatch:
    types: [hello_test]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "hello from github actions"
